spring.cloud.config.discovery.enabled: true
eureka.client.service-url.defaultZone: http://localhost:7001/eureka
eureka.client.registry-fetch-interval-seconds: 1
eureka.instance.lease-renewal-interval-in-seconds: 1
management.endpoints.web.exposure.include: health,info,env,bus-refresh,hystrix.stream