spring.cloud.config.discovery.enabled: true
eureka.client.service-url.defaultZone: http://${discovery.uri:localhost}:7001/eureka
eureka.client.registry-fetch-interval-seconds: 20
eureka.instance.lease-renewal-interval-in-seconds: 20
management.endpoints.web.exposure.include: health,info,env,bus-refresh,hystrix.stream
logging.level.root: WARN