spring.cloud.config.discovery.enabled: true
eureka.client.service-url.defaultZone: http://localhost:7001/eureka
eureka.client.registry-fetch-interval-seconds: 1
eureka.instance.lease-renewal-interval-in-seconds: 1
management.endpoints.web.exposure.include: "*"
#spring.rabbitmq.host: localhost
#spring.rabbitmq.port: 5672
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest