spring:
  cloud:
    stream:
      bindings:
        input:
          destination: message.exchange
          binder: rabbitmq
          group: message.group
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true