spring:
  cloud:
    stream:
      bindings:
        output:
          destination: message.exchange
          binder: rabbitmq
          content-type: application/x-java-object;com.example.MessageDTO