spring:
  cloud:
    stream:
      bindings:
        input:
          destination: message.exchange
          binder: rabbitmq
          group: message.group
          content-type: application/x-java-object;type=com.example.messageconsumer.MessageDTO
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true