spring:
  rabbitmq:
    listener:
      default-requeue-rejected: false
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 2
        multiplier: 1.5
        max-interval: 5000