spring:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:C:\dev\workspace\databases\h2-db;DB_CLOSE_ON_EXIT=FALSE
    username: null
    password: null
#spring.data.mongodb.uri: mongodb://localhost/test