endpoints.health.enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.H2.Driver
    url: jdbc:h2:file:C:\dev\workspace\h2-db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: 
    password: 