endpoints.health.enabled: true
management.endpoints.web.exposure.include: "*"
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:C:\dev\workspace\h2-db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: null
    password: null